### ISSUE TITLE
[BUG] FileProvider - biometrical authentication disables manual passcode input

### ISSUE THREAD

**Issue by phil1995** [owncloud/ios-app#1004]
### Steps to reproduce
1. Set passcode in the main app
2. Enable Touch ID
3. Open Files App 
4. Wait until the Touch ID prompt appears
4. Press "Enter code"-button 

### Expected behavior
The Touch ID prompt should disappear and the "Enter code"-ViewController should stay so I can enter my passcode manually

### Actual behavior
The Touch ID prompt and the "Enter Code"-ViewController disappear and if I click on "authenticate" in the files app the Touch ID prompt appears again.

### Client
**iOS version:** 14.6

**ownCloud app version:** 11.6.1

**Device model:** iPhone

**Comment by jesmrec** [comment]
Reproducible in 11.6.1 from my side. After the last changes in 11.7, dialog is dismissed after a while. Code is entered by fast fingers. We'll take a look

thanks for reporting!

**Comment by felix-schwarz** [comment]
Proposed solution / workaround:
- add a `Face|Touch ID` button to the code entry UI (similar to f.ex. 1Password) to allow biometric authentication with a single tap
- by default, do not trigger biometric authentication automatically
- trigger biometric authentication automatically **only if** the last authentication was _also_ biometric  _and_ successful
- fall back to default behaviour (do not trigger biometric authentication automatically) if the last biometric authentication attempt was not successful

Benefits:
- users who _can't_ authenticate biometrically (f.ex. due to wearing a mask) are not repeatedly prompted for biometric authentication
- users who _can_ authenticate biometrically do only need to tap the `Face|Touch ID` button once
- unnecessary prompts for users who change between the scenarios frequently are reduced to a minimum - and restoring automatic biometric authentication prompts requires only a single tap
- the problem described in this issue is addressed

**Comment by jesmrec** [comment]
Done! Ready to 11.9
