### ISSUE TITLE
[BUG] Missing (german) translations 

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios-app#1184]
### Steps to reproduce
1. tap on magnifying glass to start search
2. Set search params by tapping on `type`, `date` or `size`

### Expected behavior
List of options are translated

### Actual behavior
List options are not fully translated (shown in english)

### Client
**iOS version:** 16.2

**ownCloud app version:** Beta version 12.0 build 248 (app: fa025d0a, sdk: 5dce3ef)

**Device model:** iPhone 11 Pro

![IMG_7932](https://user-images.githubusercontent.com/16665512/220930125-7a24ad64-5360-4416-a744-e954989fbad8.PNG)
![IMG_7931](https://user-images.githubusercontent.com/16665512/220930164-647a17a6-16be-4e11-b8c3-9ef82360e81e.PNG)
![IMG_7930](https://user-images.githubusercontent.com/16665512/220930166-d9821998-2542-4268-b685-346605211df5.PNG)

**Comment by michaelstingl** [comment]
@jesmrec could you verify?

**Comment by jesmrec** [comment]
@michaelstingl verified. Those german translations are missing.

Checked with vanilla app, build 248 `0a60d26a`

**Comment by jesmrec** [comment]
In addition, in `Settings` -> `Enable Pro Features` (only debug) is also untranslated. Maybe not relevant but...

**Comment by michaelstingl** [comment]
Just not translated yet? Or not translatable? Are those strings available in Transifex?

/cc @felix-schwarz @hosy

**Comment by jesmrec** [comment]
i don't see those resources in transifex (spanish language, i'm not allowed to check german). Is it posible that those new strings are not merged yet in the transifex observed branch?

**Comment by felix-schwarz** [comment]
Fixed in #1207:

<img width="279" alt="Bildschirmfoto 2023-05-09 um 10 28 27" src="https://user-images.githubusercontent.com/639669/237039597-ef49e127-e66d-4307-8c1d-2ec0adb91cd2.png">
<img width="322" alt="Bildschirmfoto 2023-05-09 um 10 28 46" src="https://user-images.githubusercontent.com/639669/237039682-178342aa-2fc8-4da0-8c2e-279408da2537.png">
<img width="302" alt="Bildschirmfoto 2023-05-09 um 10 29 03" src="https://user-images.githubusercontent.com/639669/237039725-6da6206b-5340-4579-9894-cb11bb3f38fa.png">

> In addition, in `Settings` -> `Enable Pro Features` (only debug) is also untranslated. Maybe not relevant but...

`Enable Pro Features (QA)` is localizable, but not localized at the moment because it is destined for internal QA-use only.
