### ISSUE TITLE
[FEATURE REQUEST] Always send a language header in all requests

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1193]
**Is your feature request related to a problem? Please describe.**

Latest oCIS notifications API (`/ocs/v2.php/apps/notifications/api/v1/notifications?format=json`) responds with translated content. Other endpoints will learn this too.

**Describe the solution you'd like**

iOS app should always send a language header in all requests which follows the Accept-Language spec:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

**Describe alternatives you've considered**

_No response_

**Additional context**

Related:
- Web: https://github.com/owncloud/web/issues/8612
- Desktop: https://github.com/owncloud/client/issues/10619
- Android: https://github.com/owncloud/android/issues/3980

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
Should already work in the iOS app ✅

**Comment by felix-schwarz** [comment]
This is now fully implemented also for language codes with region/country variants and will be included in the next build.

**Comment by jesmrec** [comment]
last commit in `feature/css` branch includes the header. Some examples:

how is this set? i mean, i've tested with several languages and variants and i noticed 

| Language in device | Accept-Language |
|:-:|:-:|
| English  |  `en` |
| English (UK) |  `en-gb,en` | 
| English (US) |  `en` | 
| Spanish |  `es` | 
| Spanish (AR) |  `es` | 
| German |  `de` | 
| German (SW) |  `de` | 
| German (AUT) |  `de` | 

the variant is not set in all cases, does it depend on the system language preference? 

this is not a problem because all the responses are compliant with the spec, but it took my atention: English (UK) language shows the variant, whereas English (US), German or Spanish don't. @felix-schwarz

**Comment by felix-schwarz** [comment]
@jesmrec It depends on the system language preferences and which languages the app is localized in. The OS is asked for the intersection of preferred languages (in System Settings) and languages the app is localized in.

If f.ex. the user picks `en-gb` for the system - and the app is also specifically localized for `en-gb`, the `Accept-Language` header will contain `en-gb`. 

If there is no `en-gb` variant app localization, the header will use the next best match - likely `en`.

If the app would not ship with any `en` localization, `en` would also not be included in the header.

**Comment by jesmrec** [comment]
That works totally for me. Approved
