### ISSUE TITLE
[BUG] german translation missing

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios-app#1201]
### Steps to reproduce
1. Tap in search field in the top bar

"Saved search templates" is not translated

![IMG_B006410C9019-1](https://user-images.githubusercontent.com/16665512/234026018-db28f991-6dff-4a22-bf83-9f3046257ab0.jpeg)

**Comment by hurradieweltgehtunter** [comment]
Another:

![IMG_C450208C3A14-1](https://user-images.githubusercontent.com/16665512/234030618-0a44cac6-dafb-4c08-a272-0fcb5ff4b61b.jpeg)

**Comment by felix-schwarz** [comment]
Fixed in #1207:
![Simulator Screenshot - iPad (10th generation) - 2023-05-09 at 10 26 43](https://user-images.githubusercontent.com/639669/237039159-a6f0f561-4f1f-4a01-a5be-aafb77165c60.png)

<img width="834" alt="Bildschirmfoto 2023-05-09 um 10 23 46" src="https://user-images.githubusercontent.com/639669/237038403-da7c3fce-2ada-486b-affe-0fd91a3a5be4.png">
