### ISSUE TITLE
File list: Pull-to-Refresh glitchy 

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#142]
![screenflow](https://user-images.githubusercontent.com/214010/47748950-4a9aef00-dc8c-11e8-8e85-fd1a62e4cc4a.gif)

- White background in spinner region doesn't look good with the Classic theme
- File list "jumps back" a when pulled over trigger point
- White line stays there after Pull-to-Refresh

---

- https://github.com/owncloud/ios-app/commit/a03260ea7a92640f1df2dd2e008f07a3856e6003 on iPhone 7 Plus running iOS 12.1
- ownCloud 10.0.10

**Comment by pablocarmu** [comment]
> White background in spinner region doesn't look good with the Classic theme

The problem is that the table view background color is white, and this is the same color that the color in the spinner region, here you have an example with a yellow background. 

![simulator screen shot - iphone x - 2018-11-28 at 16 55 21](https://user-images.githubusercontent.com/8929738/49164166-e0c74100-f32e-11e8-9ad5-364c9fa4d5b7.png)

To fix this we need to set the background color of the refresh controller to the navigation's bar one.

> File list "jumps back" a when pulled over trigger point

This can be fixed coding:

```Swift
self.tableView.estimatedRowHeight = 0

override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
	return 80
}
```

> White line stays there after Pull-to-Refresh

I've tried different approaches here and I end up following what it's explained in the following StackOverflow answer. It's a pretty hacky solution but it's the only one I've found that actually solves the problem.
https://stackoverflow.com/a/50670500

The final result is:

![refreshcontrollupdate](https://user-images.githubusercontent.com/8929738/49167033-de67e580-f334-11e8-8f80-cc3ca1ad5f4c.gif)

it's this what you're expecting @michaelstingl ?

**Comment by hosy** [comment]
@pablocarmu 
I also found an (unsweet) solution, but maybe this will not break in a feature iOS release. You can set a UIView below of the RefreshControl, set the same height as the tableView and set the Y-Coordinate negative of the height.
But maybe as @felix-schwarz mentioned in the meeting, you can also try to debug the views with Xcode.

```
let gapCoverView = UIView(frame: CGRect(x: 0, y: -self.view.frame.size.height, width: self.view.frame.width, height: self.view.frame.size.height))
gapCoverView.backgroundColor = UIColor.yellow
self.view.insertSubview(gapCoverView, belowSubview: refreshControl)
```

**Comment by jesmrec** [comment]
@mneuwert @felix-schwarz are there any other options or solutions apart of the one suggested by @pablocarmu: https://github.com/owncloud/ios-app/pull/174
