### ISSUE TITLE
File list: different sorting methods

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#19]
_As a user, i want to order the list of files, so that i can find in a easier way the file i need_

AC: 

- [ ] Choose which methods to be implemented. Candidates:
 - By kind of file
 - By A - Z
 - By Z - A 
 - By date
- [ ] Set options to sort in the files view, just above the file list.
- [ ] QA

**Comment by pablocarmu** [comment]
## The design is open so if you want to contribute to it, you can! 
As we talked before, here is the UI proposal for the filter feature:

![server view work in progress](https://user-images.githubusercontent.com/8929738/40410104-30d8d4b2-5e6d-11e8-8d34-8be6dbb2e309.png)

You can see that the design is the same as the files app one. One bar on the top of the files table with three different elements:
![img_0351](https://user-images.githubusercontent.com/8929738/40410065-0fe593f8-5e6d-11e8-9770-45c9280bf85f.PNG)

1. New folder button (left): today this feature is not supported yet by the ownCloud SDK but we can code the button there and link it to the SDK action later.

2. Grid/List button(right): it changes the file list between grid view and list view.

3. Sort selector: In the **current app**, we have three different sorting methods: **A-Z, Newest-Oldest and by kind of file**. 
	
What **the files app offer** is order the files by **Name, Date, Size, and Tags.** Also, you can see that the presentation method is through an ActionSheet.
![img_0350](https://user-images.githubusercontent.com/8929738/40410067-1001354a-5e6d-11e8-9965-c1e563c290b3.PNG)

So my questions before I'll start to implement this are:

1. **_What sorting methods are we going to support?_**
I suggest A-Z, Z-A, date, size, favorites, and kind of file.

2. **_Are we going to support the creation of folders and change the view layout?_**
Otherwise, we should think about the bar design.

3. **_Are we going to present the sorting methods through an Action Sheet?_**
 Based on what I see in other apps this way is the standard way to present this kind of things.

4. **_In the settings view, should we have a per bookmark setting to select which sorting method is preferred for each user?_**

@michaelstingl @felix-schwarz @jesmrec @javiergonzper

**Comment by jesmrec** [comment]
> What sorting methods are we going to support?
I suggest A-Z, Z-A, date, size, favorites, and kind of file.

A-Z, date and kind are currently supported. Size is welcome, so Android also supports it. I don't know the point to include favourites as sorting method, so that they will have their own shortcut within the app 

> Are we going to support the creation of folders and change the view layout?
Otherwise, we should think about the bar design.

creation of folders must be supported. 
change the view layout is a nice to have. 

The bar design is OK. Could the icons for creation of folders and view layout be set as hidden until they are developed?

> In the settings view, should we have a per bookmark setting to select which sorting method is preferred for each user?

IMHO, this is not needed. We can store the latest sorting method set by the user in each bookmark, but not a new option in settings view. I would only add an option in settings in case we want a common option for all bookmarks, in this case we do not need the bar above the file list.

**Comment by michaelstingl** [comment]
PR: https://github.com/owncloud/ios-app/pull/55

**Comment by jesmrec** [comment]
Approved and merged
