### ISSUE TITLE
Share with user/groups

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#351]
_As an user, i want to share my contents with other users or groups, in my owncloud server or in another one_

AC (already defined in epic):

* User can share any file or folder with other users and groups, by searching them (using patterns) and selecting the desired one
* User will see if the file is shared and the list of sharees
* Every share has its own attributes:
   - Permissions: edit and share in case of files. add, edit, delete and share in case of folders
   - Password: will be mandatory depending capabilities
   - Expiration date: will be mandatory depending capabilities
* Federation will be allowed. with @ notation will be distinguished when the user is in a different oC instance (if capabilities allow it)

The capabilities affecting private sharing are:

- "Allow apps to use the Share API" -> if false, sharing is not available
- "Allow resharing" -> If true and the file is shared with the user, no sharing available
- "Allow sharing with groups" -> if false, groups will not appear in searching
- "Restrict users to only share with users in their groups" 
- "Restrict users to only share with groups they are member of"
- "Exclude groups from sharing"
- "Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered."
- "Default user and group share permissions"
- "Extra field to display in autocomplete results"
- Federation: allow federation, 

Some UI drafts will be welcome to discuss implementation.

related: Public Share: #275

**Comment by hosy** [comment]
I finished a first draft and I'm interested in your opinion.

Starting point is the Action-View, where you have action for an item and further informations like file name, file size, modifying date and file icon. 
My thoughts was to show there if the item is shared. If the item is shared, you can see all recipients for the share. I decided to put the names one after the other without further informations and actions, because in this view it should only give a first overview and the view has not so much space for more actions.
If the item currently is not shared, you have an action to add a new share recipient.

| ![IMG_8108-2](https://user-images.githubusercontent.com/736109/55956374-1cbacd00-5c64-11e9-8fed-390286fd916a.png) | ![IMG_8105-2](https://user-images.githubusercontent.com/736109/55956367-188eaf80-5c64-11e9-90af-aebbf7da03d2.png) |
|-------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|


If you tapped on the share recipients you will get a new sharing view, where you can see all recipients grouped by Users, Groups and Remotes. For every recipient you can see the granted permissions, without any need to look at each recipient in the detail view.
If you want to add a new share recipient, start typing into the search bar and after selecting the result the recipient a new share will be created for the item.

![IMG_8107-2](https://user-images.githubusercontent.com/736109/55956388-26443500-5c64-11e9-886c-bb83949a8bf8.png)

If you want to change the permissions, select one and a new edit view will opened. Here you can change the permissions, get more informations like the creation date for the share, revoke the share or you can see the reshares for this item by the selected user.

![IMG_8106-2](https://user-images.githubusercontent.com/736109/55956397-2c3a1600-5c64-11e9-88b6-27231a915480.png)

So, what do you think?

**Comment by jesmrec** [comment]
Some comments from my side:

- If you share an item with several users (like in the screenshot), it seems a bit overloaded. For such aim, i'd go for a list set up like in the other screenshot, and remove the recipients from there, keeping the option. In the  `Sharing` menu of the card, more options should be included, so i'd let there only the options and not the internal details of each one of them.
- In the file list, some kind of icon should mark whether the item is shared or shared with me. 
- `Revoke Sharing` in the Sharing menu would be more straightforward (swipe option?) as in the permissions
- I miss the `Delete` permission. Don't forget that the permissions are different for files and folders (files -> edit, share, folders -> create, edit, delete, share)

expecting your comments

**Comment by hosy** [comment]
I have updated two screens. All screens are (working) design drafts, but not all features are implemented (permissions, etc.).

| ![IMG_8112-2](https://user-images.githubusercontent.com/736109/55983865-61625a80-5c9c-11e9-83c1-f527e4070f84.png) | ![IMG_8113-2](https://user-images.githubusercontent.com/736109/55983866-61625a80-5c9c-11e9-9214-3dfa026fb074.png) |
|-------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|

**Comment by felix-schwarz** [comment]
I really like what I see. A couple of thoughts from my side:

1) I like the one line summary, especially when making it flexible:
- in its place, the app should show a spinner while the app fetches the shares from the server
- if no shares were retrieved, the space could turn into a "Share this file" / "Share this folder" "button" (the way the actions are currently styled in the card)
- if shares were retrieved, create a summary like in the original approach and compute if it can be shown in full:
    - if it can be shown in full, show it
    - if it can't be shown in full, show a summary of the kind "6 recipients, 1 public link"

2) I think the (+) button should be moved up from the summary line, to the right border of the "Sharing" header. And in the summary line, if there are any existing shares, a disclosure arrow to the right (like the next to "Felix" in the screenshot above) be shown.

3) I find the current permission naming in ownCloud to be confusing. Without looking at the docs, I'd have a hard time to know what f.ex. the difference between "change" and "edit" is. The UX could be improved here, f.ex. by providing presets (think "read-only", "read, write", "read, write and share" "custom") and/or adding brief explanations directly below the names of the permissions so users know what the permissions mean.

4) Regarding presets, this should become relevant again for public links. There may also be customers who'd like to configure their own presets - or which presets are available (@michaelstingl will know more about this).

5) Finally, a general thought on the space used by the actions:

We have a lot of whitespace around the action names right now. If we want to reclaim some of that space, one possible solution would be to turn them into icons (similar to the iOS share sheet) and layout them horizontally or as a grid.

Since we already have an Action class for every action, and also the ability to provide different images for different locations (toolbar, more card, …), this could be pretty straight forward.

Looking ahead and seeing the addition of more specialized actions (like "Scan document"), this would also scale better.

**Comment by michaelstingl** [comment]
> 5\. Finally, a general thought on the space used by the actions:
> 
> We have a lot of whitespace around the action names right now. If we want to reclaim some of that space, one possible solution would be to turn them into icons (similar to the iOS share sheet) and layout them horizontally or as a grid.
> 
> Since we already have an Action class for every action, and also the ability to provide different images for different locations (toolbar, more card, …), this could be pretty straight forward.

@felixboehm Could you provide a quick sketch to illustrate your idea?

**Comment by felix-schwarz** [comment]
@michaelstingl Sure. Here are two possible designs:

1) In a grid
![Actions](https://user-images.githubusercontent.com/639669/56031999-41c14580-5d21-11e9-8d17-b05f069a2fb1.gif)

2) In one row:
- placing the most frequently used actions first
- if there are more actions than fit horizontally, indicate there are more actions by ensuring the last visible action is only partially visible

![Actions-2](https://user-images.githubusercontent.com/639669/56032065-6fa68a00-5d21-11e9-8a73-1cff20971a39.gif)

**Comment by hosy** [comment]
@felix-schwarz thank you for your ideas. I more like version 1. in a grid. Because I don't like it to scroll until I see the action I need.
Space is better used and all actions are visible. The only thing I'm not sure about if labels working with long translations.

**Comment by hosy** [comment]
I have added info messages for the permissions in edit view. These messages are hidden, until you tap on the `Info` button on the top right. If you do not need help, you have a clean UI, but if you need more informations, you can show the info messages.

![IMG_8116-2](https://user-images.githubusercontent.com/736109/56045063-c2dc0500-5d40-11e9-8c2a-0b297ffb55e5.png)
