### ISSUE TITLE
[UI / PDF] Full screen view for PDFs

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#428]
In the PDF view, the toolbar is always shown and the miniatures are always shown. Many PDF viewers can switch to a fullscreen view…

**Comment by mneuwert** [comment]
@michaelstingl Played around with adding tap gesture recognisers and came to the conclusion:
- We can add tap to full-screen
- But we will loose double tap zoom... And that's not easy to fix. Tried some hacky approaches but failed so far..

**Comment by michaelstingl** [comment]
> * But we will loose double tap zoom... And that's not easy to fix. Tried some hacky approaches but failed so far..

Try that with the 11.5 TestFlights, maybe with the 11.5 stable as well, then wait for user feedback? We can always revert…

**Comment by mneuwert** [comment]
@michaelstingl @hosy Changed couple of things due to issues with thumbnail view which sort of started behaving correctly on iOS13, before it has been behaving pretty badly causing all sorts of crashes when it's properties (layout, thumbnail size) have been changed dynamically. So, I decided to provide cool stuff on iOS 13 or higher:

- Full screen when PDF view is tapped
- Dynamically adapting thumbnail sizes
- Vertical thumbnail strip in landscape on iPhone (compact vertical size class).
- Background colour of thumbnail strip matching system default PDF view background color which is nicer than the one used prior to iOS 13

**Comment by jesmrec** [comment]
Done
