### ISSUE TITLE
Add a "Create Folder" button in ClientDirectoryPickerViewController

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#443]
### Steps to reproduce
1. Move or Copy an item in the App
2. `ClientDirectoryPickerViewController` will appear
3. This view should have to option to create a new folder in the selected directory

### Expected behaviour
No option to add a new folder

### Actual behaviour
Button on the left top to create a new folder

### Client
**iOS version:**
12.3

**ownCloud app version:**
1.0.2 (125)

**Comment by jesmrec** [comment]
Let's QA this

**Comment by jesmrec** [comment]
### (1)

I am able to share content from the Safari browser, for example a PDF file. But, in Photos app, the ownCloud app does not appear to share with. do i miss something? 

Safari:
![Screenshot 2019-07-24 at 16 35 14](https://user-images.githubusercontent.com/14894746/61802603-0d394b80-ae31-11e9-9f7b-dfe47a10737e.png)

Photos app:

![Jul-24-2019 16-37-07](https://user-images.githubusercontent.com/14894746/61802762-538eaa80-ae31-11e9-99b2-cfe9f15f8105.gif)

of course, both screenshots were taken with the same device with the ownCloud app installed.

**Comment by jesmrec** [comment]
only as a tip, out of scope of this issue: If a user has two accounts in the same server (f.ex., an user account and an admin account) with the same full name, accounts can not be distinguished:

![Screenshot 2019-07-24 at 16 56 59](https://user-images.githubusercontent.com/14894746/61804355-14158d80-ae34-11e9-91ec-d1ceb9dc13ab.png)

this is out of scope because the same issue happens in the account list. i will open a separate issue about that.
