### ISSUE TITLE
[PDF-UX] Fix thumbnail size on iPad

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#515]
Size of the thumbnails when PDF is viewed on the iPad is not optimal. See screenshot:

![IMG_0051](https://user-images.githubusercontent.com/228537/66153454-d85d2800-e61b-11e9-967a-062431e8c37b.jpg)

**Comment by hosy** [comment]
Agree! It would be also good, to put the thumbnail view on the right side , if the device is in landscape mode, because if the device is an iPhone, you don't have so much space for the document left.

![Simulator Screen Shot - iPhone Xs - 2019-10-04 at 08 57 24](https://user-images.githubusercontent.com/736109/66187456-1f333800-e685-11e9-89d3-54ae1dab670a.png)

**Comment by mneuwert** [comment]
@hosy this should be fixed with PR #813, although it is mostly true for iOS 13.x and higher

**Comment by jesmrec** [comment]
Done
