### ISSUE TITLE
Include new dialog to encourage users to add a new app review in App Store

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#540]
See related Android issue https://github.com/owncloud/android/issues/2071

**Comment by felix-schwarz** [comment]
To ensure that only users who have actually been using the app for a while - and thereby improve the quality and fairness of the reviews - some criteria should be met before prompting the user for a review:
- at least 14 days have elapsed since the first launch of the app (to ensure the app has actually been used for a while)
- at least 7 days have elapsed since the first launch of _this version_ of the app (to ensure the version of the app that the review would be about has actually been used for a while)
- at least one bookmark has been added (to not prompt users who have never set up or connection to a server - and therefore not really used the app)

**Comment by michaelstingl** [comment]
> * at least 130 days have elapsed since last prompting the user for a review (to not annoy the user)

Better 230 days before asking again?

**Comment by mneuwert** [comment]
@michaelstingl just for clarification, do we eventually also want to include deep link to review page in settings for instance, to let users to add reviews any time they feel happy?;-)

Here excerpt from Apple Documentation:

_...In addition, you can continue to include a persistent link in the settings or configuration screens of your app that deep-links to your App Store product page. To automatically open a page on which users can write a review in the App Store, append the query parameter action=write-review to your product URL..._

**Comment by michaelstingl** [comment]
@mneuwert Sure, why not 👍

**Comment by jesmrec** [comment]
Done! ready to 11.4
