### ISSUE TITLE
Ugly error caused after losing OAuth2 credentials

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#585]
This comes from 1.2 version: https://github.com/owncloud/ios-app/issues/550#issuecomment-565382903

Token removal/dismisal during uploads causes an ugly error:

1. Login with OAuth2
2. Start to upload a bunch of files (f.ex, an album with 50 videos)
3. While it is being uploaded, remove token (webUI -> Settings -> Security - Oauth2 -> remove iOS app as authorized)
4. Get a new token by signing in

Current: Ugly error when retries the pending uploads

![IMG_1086](https://user-images.githubusercontent.com/14894746/70792274-1f446800-1d99-11ea-9da1-b2fe74c563dd.PNG)

Dialog is not dismissed neither cancelling nor retrying. It raises again.

iPhoneX v13.2
iPAdPro v13.2

**Comment by felix-schwarz** [comment]
I feel this edge case can't currently be adequately addressed:
- if an upload fails due to a non-recoverable error, the user needs to know
- retrying will retry the upload and run into the same error, letting the user know again
- cancelling will cancel and remove the upload

### Workaround:
The only way to escape this infinite loop (without cancelling the upload) is to 
- put the device in airplane mode
- log out of the account
- edit the bookmark
- turn off airplane mode and log back into the account

### Proposed Solution:
This should be addressed by the already planned move of errors to a list section in the `Status` tab, where users can interact with them on their own schedule - and without modally blocking the entire UI.

**Comment by jesmrec** [comment]
Fixed in #662. To be released in 11.4
