### ISSUE TITLE
[BUG] Markup feature with HEIC files

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#617]
### Steps to reproduce
1. Open an HEIC image
2. Mark it up with signature, magnifier, shapes... 
3. Save it, no matter whether overwriting or saving in new file

### Actual behaviour
Changes are not saved. 

### Expected behaviour
Changes saved

### Client
**iOS version:** 13.3

**ownCloud app version:** 1.3.0

**Device model:** iPhoneX

**Comment by hosy** [comment]
I just figured out how markup for HEIC files will be saved:

- Add a markup to a HEIC file
- Before you tap Done, end editing by tapping on the selected Markup button
- Tap on Done and save as copy or overwrite original
For me this is an iOS bug, because the delegate does not return a new file, until the editing was ended. Unfortunately we cannot end editing by code.

**Comment by jesmrec** [comment]
Ok, let's wait then for Apple's fix. We should not forget this in case of complaining users.
