### ISSUE TITLE
[BUG] Signature in PDF files

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#618]
### Steps to reproduce
1. Open a PDF to markup
2. Click on  '+' and select Signature
3. Add a signature, wherever the place in the PDF
4. Save

### Actual behaviour
Open the file after saving, and the signature is not there

### Expected behaviour
Open the file after saving, and the signature is there

### Client
**iOS version:** 13.3

**ownCloud app version:** 1.3.0

**Device model:** iPhoneX

**Comment by hosy** [comment]
Sounds like an iOS bug. What happens, if you sign the document and as an addition draw inside?

**Comment by jesmrec** [comment]
If i only draw, strokes are correctly saved.
If i only sign, signature is not saved.
If i sign and draw together, nothing is saved.

**Comment by hosy** [comment]
I just figured out how a signature will be saved:
- Add a signature to PDF
- Before you tap `Done`, end editing by tapping on the selected Markup button
- Tap on `Done` and save as copy or overwrite original 

For me this is an iOS bug, because the delegate does not return a new file, until the editing was ended. Unfortunately we cannot end editing by code.

**Comment by jesmrec** [comment]
Ok, let's wait then for Apple's fix. We should not forget this in case of complaining users.
