### ISSUE TITLE
[BUG] Sorting by type confusing

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#670]
### ownCloud iOS app 1.3.2

![2020-04-15 23 38 32](https://user-images.githubusercontent.com/214010/79392244-5e670d80-7f73-11ea-9f1b-3c2e2d6a1885.png)

### iOS Files app

![2020-04-15 23 41 55](https://user-images.githubusercontent.com/214010/79392250-60c96780-7f73-11ea-89d0-4a96a19769d5.png)

### Client
**iOS version:**
13.4.1

**ownCloud app version:**
1.3.2

**Device model:**
iPad Pro 12.9"

**Comment by felix-schwarz** [comment]
Should be fixed as of https://github.com/owncloud/ios-app/pull/648/commits/0c1c58227e3626f16c9728336b70603c2e507ea7 (#648)

Changes made:
- PDF viewer (in OC app) can now also view Illustrator files
- rename "type" to "kind" to match Files app
- for "kind" sort method, use kind (file/folder), then suffix, then MIMEType for sorting
- override UTI type for `ai` files in Files Provider, as iOS returned a bogus UTI for `application/illustrator` – Files app no longer shows the icon as greyed out now

**Comment by jesmrec** [comment]
QA checks:

- [X] ai files are currently open inside the app within the PDF Viewer
- [X] ai files are not greyed out in Files app anymore
- [X] Type -> Kind as sorting method (wording)
- [X] Criteria in Kind sorting: File/Folder - Extension - MIME

Approved.

Nothing to merge since this fixes are included in the milestone branch. Let me know if i'm wrong.

**Comment by jesmrec** [comment]
Done
