### ISSUE TITLE
[FEATURE REQUEST] Setting to delete an uploaded media on target folder when deleted on IOS

### ISSUE THREAD

**Issue by mmattel** [owncloud/ios-app#712]
**Describe the solution you'd like**
Have a setting, which could be independently enabled on each media type (photo/video), which deletes the target on the target folder (only if present), when it got deleted on the IOS device.
More or less a trigger on the delete media event, check if the media is present on the target, and delete it.

It would be also great to have a setting to do this the opposite way.
When deleted on the target folder, delete it on the device if present.
I would not do that automatically, but enable it with a setting only.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

@michaelstingl @hosy

**Comment by mneuwert** [comment]
@mmattel Do you want to detect when user deletes the media file in the system's photo library? I think that's going to be tricky.. since the only reliable way to identify the asset in iOS is to use it's local identifier (sort of UUID). When we export and upload the item we loose this connection. We can't identify uploaded file by PhotoLibrary local ID. To be able to do that we would need to maintain a database / key-value store storing relation between local asset ID and uploaded item ID.

Also IMHO this is pretty dangerous feature in terms of possible undesired data loss.

**Comment by mmattel** [comment]
I do not know in detail if exists, but if there would be a hook in IOS we could connect to, the idea is, if a photo gets deleted in IOS to trigger the app and check if that photo is present on the target upload folder and delete it there too.

With prio 2, the other way round would be, that if a photo gets deleted or moved in the target upload folder, it gets deleted in IOS. Your point btw is valid, therefore it needs more thinking if that is valid.

**Comment by michaelstingl** [comment]
@mmattel Thanks for sharing the idea and thanks a lot @mneuwert for providing some background. I don't plan to implement this. Also no plans to implement the 2nd idea.

I could imagine, to trigger deletion of the local copy, after a media file has been uploaded to ownCloud (to free up local space), but this would require another issue…
