### ISSUE TITLE
[BUG] Exporting renamed files have still the former filename

### ISSUE THREAD

**Issue by mmattel** [owncloud/ios-app#825]
### Steps to reproduce
1. open a file which is stored in a google drive backend (mount with longer backend response time)
2. rename this file (works)
3. export the renamed file to mail

### Expected behavior
The attached file should have the NEW filename

### Actual behavior
The attached file has the OLD filename

To overcome this, you have to go one folder level lower and up again, then exporting works with the new filename. Maybe there is no wait for the response from the server to update the internal app database. A refresh seems only to be made when the folder gets requeried.

### Client
**iOS version:** 14.01

**ownCloud app version:** 11.4.1 build 172

**Device model:** iPhone SE / iPad 9.7" 

### Server configuration
**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.3

**ownCloud version:** 10.5

**Storage backend (external storage):** smb, gd, ftp, local

@michaelstingl @mneuwert @hosy FYI

**Comment by michaelstingl** [comment]
@mmattel could you try to reproduce with demo.owncloud.com or demo.owncloud.org ?

**Comment by mmattel** [comment]
@michaelstingl just tried.
- connected the ios app to demo.owncloud.com
- added a sample pdf file via the browser (was immediately seen in the ios app)
- in the ios app, renamed that file
- action/export to mail -> new name was used

I interpret this as follows: The app uses the old name as long there is a update response from the server after renaming. For quick responses like you get with local drive this does not matter, but for longer taking responses like on GD, you get a noticable time gap between old and new name.

**Proposal:**
when doing a rename, disable all items in actions as long there is no server response (success/deny) processed. This would prevent such issues.

**Comment by felix-schwarz** [comment]
@mmattel @michaelstingl I managed to reproduce the issue by:
- downloading a file
- turning on Airplane Mode
- renaming the file in the app (offline)
- using the "Open In" action on the file to bring up the share sheet

While the app's database - and therefore what's shown in the File Provider and app - is updated right away following a rename, the actual file on disk is only renamed once the rename has completed on the server.

And since iOS uses the file's name on disk (even if providing a different name via `UIDocumentInteractionController.name`), you got the old name.

https://github.com/owncloud/ios-app/commit/99dee537c55c01edfa9dd6c7931c118e589912b3 fixes the issue by creating temporary clones of the file(s) to share, using the item's name - then removing the clones again once the action completes.

**Comment by jesmrec** [comment]
Problem is fixed and will be out in 11.4.2
