### ISSUE TITLE
[MDM] [iOS14] com.apple.developer.associated-domains.mdm-managed

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#828]
- https://developer.apple.com/videos/play/wwdc2020/10139/
- https://developer.apple.com/forums/content/attachment/b0e4bcb1-83e0-4936-bc27-4d509e03e615

MN: Looks like it is independent from SSO

**Comment by mneuwert** [comment]
To me it looks like that there is nothing to be done in the app itself. Just a matter of MDM solution supporting it. And then associated domains could be used as if they were configured at build time...

https://developer.apple.com/documentation/devicemanagement/associateddomains

**Comment by michaelstingl** [comment]
We’d need to add syntax to the docs. 

Needs special entitlement in the profiles? Special build settings?

**Comment by mneuwert** [comment]
@michaelstingl 
My understanding is, that there are following significant changes introduced by Apple in area of associated domains:
- App still can provide an associated domain entitlement which is part of the IPA and is therefore statically added at build time.

- Otherwise, same entitlement can be provided as a new MDM payload and this one can be reconfigured by the admin and updated dynamically.  See section AppManagement: https://developer.apple.com/documentation/devicemanagement/profile-specific_payload_keys. In the MDM solution we use for testing, I didn't see that this new key is supported however. Not sure if there is some UI allowing to add custom keys.

- Apple starting with iOS 14 allows adding a query parameter to fully qualified domain name specified in associated domains entitlement allowing to by-pass new CDN mechanism used to download apple-app-site-association file. This is useful if domain is not reachable for some reason by Apple CDN (Server not visible in internet, hidden behind VPN etc.). This is described at the bottom of following article: https://developer.apple.com/documentation/safariservices/supporting_associated_domains (?mode=[developer, managed])

**Comment by mneuwert** [comment]
I think I understood what associated domains changes respective MDM have actually been applied to iOS 14:
- So looks like dynamic configuration payload is only available on macOS
- App store distributed apps use Apple CDN to cache apple-app-site-association which the server still has to provide (default behavior, same requirements as before)
- For testing developer builds, you can add ?mode=developer to URL to skip CDN (works only with Development provisioning profile)
- Managed apps using server e.g. behind VPN can use ?mode=managed merely to skip CDN caching.. but works wiht any provisioning profile.
- But still, for iOS apps associated domains are to be configured at build time via entitlement.
- Don't think there is a need to file support incident for that.
