### ISSUE TITLE
[Previews] Image gallery

### ISSUE THREAD

**Issue by javiergonzper** [owncloud/ios-app#85]
_As a user, i want the possibility see the images of a folder on the ownCloud iOS App_

### AC:
 - [ ] When the user select an image on the `File list` the gallery should be open showing the selected image
 - [ ] The gallery load all the images in the order of the `File list`
 - [ ] The gallery should have in memory the current image, the next and the previous one
 - [ ] The files should be cached
 - [ ] Pinch to zoom
 - [ ] The gallery should allow full screen with one tap on the screen and exit from background with one tap
- [ ] The image have to be loaded touching the limits of the screen on the higher size (including under `Navigation bar` and `Status bar` to prevent blinks when  enter on full screen)
- [ ] The title on the `Navigation bar` have to change once the new image are over the middle of the transition
- [ ] The transition should have a separation between images

### Mockups:
Image preview
<kbd>
![01 image preview loading](https://user-images.githubusercontent.com/1815050/41655644-bfdc1c24-748d-11e8-88bb-d6cadb872d4e.png)
</kbd>
<kbd>
![image preview 1](https://user-images.githubusercontent.com/1815050/41652473-6ded6ae4-7483-11e8-8b01-4ffccb916390.png)
</kbd>

Transition
<kbd>
![image preview 2 - transition](https://user-images.githubusercontent.com/1815050/41652542-aa1d93b8-7483-11e8-9736-6b89f51106ee.png)
</kbd>

Transition loading
<kbd>
![02 image preview transition loading](https://user-images.githubusercontent.com/1815050/41655621-ab24f044-748d-11e8-91f2-8ff9ac2c391f.png)
</kbd>

Image portrait
![image preview 3](https://user-images.githubusercontent.com/1815050/41652555-b9acf580-7483-11e8-8895-9619143e4b26.png)

Image portrait full screen
![image preview 4](https://user-images.githubusercontent.com/1815050/41652571-c86ebbf8-7483-11e8-8b7f-c276db5005ef.png)

Image landscape full screen
![image preview 5](https://user-images.githubusercontent.com/1815050/41652578-cf39d706-7483-11e8-81ef-e1a40caece3e.png)

Figma design:
https://www.figma.com/file/Ui4YzD3oQcxJSbzBEr80O9eU/Working-Draft-UI?node-id=1746%3A228

**Comment by jesmrec** [comment]
the easier, the better. Works for me.

**Comment by michaelstingl** [comment]
Cool idea from @atwm : 

> Previews for RAW files (photos). Raw files normally include jpeg previews which can be extracted and shown

Sounds feasible (for later release). This is what a quick Google search brought up: https://gentlemencoders.com/how-raw-works-on-ios/

**Comment by atwm** [comment]
I think to start off with, it would already be enough to show the embedded jpeg in the file overview. This would save resources (bandwidth, disk space). (Rather be fast than accurate) In particular for a file that has not been downloaded. My use case is that I go to the Files app and select the photos I want to continue to work on. Then I use a RAW editor (Affinity Photo, LightRoom CC, etc ) download and edit. 

Of course, if a File has been downloaded, the iOS Raw decoder could be used to show an improved preview. 

But to begin with, I really would settle for the embedded preview. Dropbox supports this and it is one of the reasons that I use Dropbox instead of ownCloud. Only seeing a generic file icon when looking through several dozens of RAW files, without knowing what you are dealing with is frustrating.

**Comment by jesmrec** [comment]
Done!
