### ISSUE TITLE
[RELEASE] ios-app 11.5.1

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#899]
Release a new version

Xcode version to work with:
12.2

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [ ] [TRFX] Update translations from transifex branch.
- [ ] [TRFX] Check for missing translations. Ping @cscherm
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [DEV] Changelog: Created a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
- [x] [DEV] Changelog: Moved all changelog files from the unreleased folder to the new version folder
- [x] [QA] QA checks -> https://github.com/owncloud/ios-app/issues/899#issuecomment-780576060
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [ ] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

**Comment by jesmrec** [comment]
Release notes 11.5.1

### QA

This is a minor version, so no complete regression test is done. Tasks performed:

**- [Crash in iOS12](https://github.com/owncloud/ios-app/pull/897)**

Installed from scratch ✅ 
Upgrading from 11.5 (where it crashed) ✅ 

Tested in 12.4 simulator, due to lack of iOS12 device

**- Accessibility fix**

The bar indicator to close the card did not have the accessibility pointer available, so, it was not recognized by Voice Over. 

Initially, it was tested with IPhoneXR iOS14.2 and the problem wasn't seem to be fixed. After upgrading the device to 14.4 it was fixed, so probably something wrong happened with the combination of device and iOS version. It was approved as well.

Following days, the accessibility tests will be reviewed to accomplish a better scenario coverage

**- Smoke test**

Basic features tested in the new version, as smoke test:

Auth: basic, oauth2 and oidc ✅ 
Download files ✅ 
Upload files form Gallery ✅ 
Upload from Files ✅ 
Share link ✅ 
Share by user ✅ 


**- Upgrade** 

iOS12: tested with the first fix, mentioned above 

|.| From 11.4.5 | From 11.5 |
|:-:|:-:|:-:|
|iOS13| ✅ | ✅ |
|iOS14| ✅ | ✅  |

So, version is approved from my side

Approved commits:

app: `e0acae81`
sdk: `e774c75`

Xcode version:  `12.2 (12B45b)`
