### ISSUE TITLE
Download file

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#93]
Although the responsibility of downloading a file will be mainly in the SDK, some points to be in account when a user wants to download a file:

- Tap on the file in file list view should trigger the download
~~- File options should contain also in the three dot menu~~
~~- Option included in multiselection mode. This (maybe) should be handled separalety~~
- Progress of the download to be displayed, with possibility of pause/resume (needed support to chunked uploads and controls in SDK). Also, to think in multiselection.
- Possibility of cancelling download before finishing
- Once the file is downloaded, file preview is triggered (if it is not a multiselected item)

more ideas welcomed

**Comment by michaelstingl** [comment]
Please try to **not use** download in file action for first version. I'd like to simplify things and have only "available offline". Download should only be triggered from other actions like preview etc. Downloaded files should be removed with a manual action from the setting screen, or if iOS system needs more space.

**Comment by javiergonzper** [comment]
@michaelstingl is right, we have to be careful with how to call "Download". Because downloads are 2 different things:

- Preview file: The file is cached when the user tap on it in order to be preview (will be deleted by the system when iOS need free storage). Epic Issue related: https://github.com/owncloud/ios-app/issues/68
- Available Offline: When the user select a file/folder (or multiple of them) to be `Available Offline` in order to have it (them) always available. This can be selected from `Multiselection` and also from the `More button`

About `Cancel` we have to design the behavior to know if we need an explicit cancel button or not.
**Without cancel button:**
- Preview file: After enter on a preview if you tap on back the cache of the file will be canceled if the download was in progress.
- Available Offline: If you mark the file as "Not available offline" the files will be deleted/canceled

PROS: The app will have a very clear touch->action behavior
CONS: If a user want to preview a very huge file he will have to wait until the file is cached. Of course exist the possibility to mark it as `Available Offline` (that should be the right user behavior because a cached file could be deleted on any moment).

**With cancel button:**
- Preview file: After enter on a preview on the bottom you can see the progress and cancel it. If you tap on back the file will still being download. If you select a second file this second file will be download before the previous one (implementing a LIFO Queue process)
- Available Offline: If you mark the file as "Not available offline" the files will be deleted/canceled. But also if you enter on a preview of a file while it is downloading you will have the `Cancel button`. This button should cancel the download and also remove the file from the `Available Offline` (asking to the user before to know if he cancel it will be removed from `Available Offline`).

PROS: A file could be cached while the user perform other actions
CONS: The user lose the focus of the file that it is caching

What do you think?
CC: @jesmrec @michaelstingl

**Comment by michaelstingl** [comment]
> What do you think?

No strong opinion here. Start with the simple approach and iterate over actual user demand…

**Comment by jesmrec** [comment]
IMHO, all actions that takes time (like a huge file download) should let the user to cancel explicitly. So, i would set a `Cancel`

**Comment by michaelstingl** [comment]
> * Option included in multiselection mode. This (maybe) should be handled separalety

I don't see the use case for (explicit) Download and multiselect for now. (Implicit) Download will happen automatically when a user opens a file, and multiselect should also work for "Available Offline".

**Comment by jesmrec** [comment]
agreed. "Downloaded" will not be an status of items.

**Comment by jesmrec** [comment]
Done
